name: lucky flake ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    timeout-minutes: 30
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: cachix/install-nix-action@master

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Check flake outputs
        run: nix flake check --print-build-logs

      - name: Check formatting and linting
        run: nix fmt -- --ci

  generate-matrix:
    timeout-minutes: 10
    runs-on: self-hosted
    outputs:
      hosts: ${{ steps.set-matrix.outputs.hosts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: cachix/install-nix-action@master

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - id: set-matrix
        name: Generate NixOS Configurations Matrix
        run: |
          HOSTS="$(nix eval --json .#nixosConfigurations --apply 'cfgs: builtins.attrNames cfgs')"
          echo "hosts=$HOSTS" >> "$GITHUB_OUTPUT"

  eval:
    needs: [check, generate-matrix]
    timeout-minutes: 60
    runs-on:
      - self-hosted
    strategy:
      matrix:
        host: ${{ fromJson(needs.generate-matrix.outputs.hosts) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: cachix/install-nix-action@master

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Evaluate NixOS configuration (${{ matrix.host }})
        run: nix eval --raw .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.drvPath
